import { useState, type FormEvent } from "react";
import { useQuery } from "@tanstack/react-query";
import { Copy, Link2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { cancelLegalDocumentRequest, createLegalDocumentRequest, issueLegalDocumentRequestLink, listLegalDocumentRequests, reviewLegalDocumentRequest, submitLegalDocumentRequest } from "@/lib/api/legal-operations";
import { downloadLegalDocument, listLegalDocuments } from "@/lib/api/legal";
import type { LegalDocumentRequest } from "@/types/legal-operations";
import type { LegalDocumentCategory } from "@/types/legal";
import { LegalField } from "../LegalShared";
import { DOCUMENT_CATEGORIES, legalDate, selectClassName, useLegalAction } from "../legal-ui";
import { OperationPanel, OperationReasonDialog, OperationRecords } from "./OperationPanel";
import { canAccessOperationCategory, operationsKey, type LegalOperationsProps } from "./operations-ui";

const REQUEST_STATUS = { open: "Aguardando documento", uploading: "Envio em andamento", submitted: "Aguardando revisão", approved: "Aprovado", rejected: "Correção solicitada", cancelled: "Cancelado" } as const;

export function LegalDocumentRequests(props: LegalOperationsProps) {
  const requests = useQuery({ queryKey: operationsKey(props, "document-requests"), queryFn: () => listLegalDocumentRequests(props.legalCase.id) });
  const documents = useQuery({ queryKey: operationsKey(props, "request-documents"), queryFn: () => listLegalDocuments(props.legalCase.id) });
  const [creating, setCreating] = useState(false);
  const [title, setTitle] = useState("");
  const [instructions, setInstructions] = useState("");
  const [category, setCategory] = useState<LegalDocumentCategory>("general");
  const [due, setDue] = useState("");
  const [attach, setAttach] = useState<LegalDocumentRequest | null>(null);
  const [documentId, setDocumentId] = useState("");
  const [review, setReview] = useState<{ request: LegalDocumentRequest; decision: "approved" | "rejected" | "cancelled" } | null>(null);
  const [link, setLink] = useState<{ url: string; expires_at: string; title: string } | null>(null);
  const action = useLegalAction();
  const owner = props.legalCase.owner_id === props.workspace.user_id;
  async function create(event: FormEvent) { event.preventDefault(); if (await action.run(() => createLegalDocumentRequest(props.legalCase.id, { title: title.trim(), category, instructions: instructions.trim(), due_at: due ? new Date(due).toISOString() : null }), "Solicitação de documento criada")) { setCreating(false); setTitle(""); setInstructions(""); setDue(""); } }
  const pendingRequests = (requests.data ?? []).filter((request) => !["approved", "cancelled"].includes(request.status)).length;
  return <OperationPanel title="Solicitação e revisão de documentos" description="Defina o que falta, receba o arquivo com acesso restrito e registre a revisão do responsável." actions={props.canEdit ? <Button size="sm" onClick={() => setCreating(true)}>Solicitar documento</Button> : null}>
    {requests.data?.length ? <p className="text-sm text-muted-foreground">{pendingRequests} {pendingRequests === 1 ? "solicitação pendente" : "solicitações pendentes"}</p> : null}
    <OperationRecords pending={requests.isPending} error={requests.error} retry={() => void requests.refetch()} empty="Nenhum documento solicitado" count={requests.data?.length ?? 0}>{requests.data?.map((request) => {
      const document = documents.data?.find((item) => item.id === request.document_id);
      const awaiting = request.status === "open" || request.status === "rejected";
      return <div key={request.id} className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div className="min-w-0"><p className="break-words font-medium">{request.title}</p><p className="mt-1 text-xs text-muted-foreground">{DOCUMENT_CATEGORIES[request.category]}{request.due_at ? ` · Solicitar até ${legalDate(request.due_at, true)}` : ""}</p></div><Badge variant={request.status === "rejected" ? "outline" : "secondary"}>{REQUEST_STATUS[request.status]}</Badge></div>{request.instructions ? <p className="whitespace-pre-wrap break-words text-sm">{request.instructions}</p> : null}{request.review_note ? <p className="rounded-md bg-muted/40 p-3 text-sm">Revisão: {request.review_note}</p> : null}<div className="flex flex-wrap gap-2">{document ? <Button size="sm" variant="outline" disabled={action.pending} onClick={() => void action.run(() => downloadLegalDocument(document), "Download iniciado")}>Baixar documento recebido</Button> : null}{props.canEdit && awaiting ? <><Button size="sm" variant="outline" disabled={action.pending} onClick={() => void action.run(async () => { const result = await issueLegalDocumentRequestLink(request.id); setLink({ ...result, title: request.title }); }, "Link de envio gerado")}><Link2 className="mr-2 h-4 w-4" aria-hidden />Gerar link de envio</Button><Button size="sm" variant="outline" onClick={() => { setAttach(request); setDocumentId(""); }}>Vincular arquivo do caso</Button></> : null}{owner && request.status === "submitted" ? <><Button size="sm" disabled={action.pending} onClick={() => setReview({ request, decision: "approved" })}>Aprovar documento</Button><Button size="sm" variant="outline" disabled={action.pending} onClick={() => setReview({ request, decision: "rejected" })}>Solicitar correção</Button></> : null}{props.canEdit && !["approved", "cancelled"].includes(request.status) ? <Button size="sm" variant="ghost" disabled={action.pending} onClick={() => setReview({ request, decision: "cancelled" })}>Cancelar solicitação</Button> : null}</div></div>;
    })}</OperationRecords>
    <Dialog open={creating} onOpenChange={(value) => { if (!action.pending) setCreating(value); }}><DialogContent><DialogHeader><DialogTitle>Solicitar documento</DialogTitle><DialogDescription>A solicitação será registrada no caso. O compartilhamento do link é uma ação manual.</DialogDescription></DialogHeader><form onSubmit={(event) => void create(event)} className="space-y-4"><LegalField label="Documento solicitado">{(id) => <Input id={id} required maxLength={150} value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Ex.: Comprovante de endereço" />}</LegalField><LegalField label="Categoria do documento">{(id) => <select id={id} className={selectClassName} value={category} onChange={(event) => setCategory(event.target.value as LegalDocumentCategory)}>{Object.entries(DOCUMENT_CATEGORIES).filter(([value]) => canAccessOperationCategory(props, value)).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>}</LegalField><LegalField label="Orientações para o envio">{(id) => <Textarea id={id} maxLength={1000} value={instructions} onChange={(event) => setInstructions(event.target.value)} />}</LegalField><LegalField label="Data desejada">{(id) => <Input id={id} type="datetime-local" value={due} onChange={(event) => setDue(event.target.value)} />}</LegalField><DialogFooter><Button type="button" variant="outline" onClick={() => setCreating(false)}>Cancelar</Button><Button type="submit" disabled={action.pending || !title.trim()}>Criar solicitação</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={Boolean(attach)} onOpenChange={(value) => { if (!value && !action.pending) setAttach(null); }}><DialogContent><DialogHeader><DialogTitle>Vincular documento recebido</DialogTitle><DialogDescription>Selecione um arquivo da mesma categoria já guardado na aba Documentos deste caso.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); if (attach) void action.run(() => submitLegalDocumentRequest(attach.id, documentId), "Documento encaminhado para revisão").then((saved) => { if (saved) setAttach(null); }); }}><LegalField label="Arquivo do caso">{(id) => <select id={id} className={selectClassName} value={documentId} required onChange={(event) => setDocumentId(event.target.value)}><option value="">Selecione um documento</option>{documents.data?.filter((document) => document.category === attach?.category).map((document) => <option key={document.id} value={document.id}>{document.display_name}</option>)}</select>}</LegalField><DialogFooter><Button type="button" variant="outline" onClick={() => setAttach(null)}>Cancelar</Button><Button type="submit" disabled={action.pending || !documentId}>Enviar para revisão</Button></DialogFooter></form></DialogContent></Dialog>
    <Dialog open={Boolean(link)} onOpenChange={(value) => { if (!value) setLink(null); }}><DialogContent><DialogHeader><DialogTitle>Link de envio seguro</DialogTitle><DialogDescription>Compartilhe este link com a pessoa que enviará o documento. Ele permite um envio e expira em {legalDate(link?.expires_at, true)}.</DialogDescription></DialogHeader><LegalField label="Link para envio do documento">{(id) => <Input id={id} readOnly value={link?.url ?? ""} onFocus={(event) => event.target.select()} />}</LegalField><DialogFooter><Button type="button" variant="outline" onClick={() => setLink(null)}>Fechar</Button><Button onClick={() => { if (link) void action.run(() => navigator.clipboard.writeText(link.url), "Link copiado"); }} disabled={action.pending}><Copy className="mr-2 h-4 w-4" aria-hidden />Copiar link</Button></DialogFooter></DialogContent></Dialog>
    <OperationReasonDialog key={review?.request.id + ":" + review?.decision} open={Boolean(review)} onClose={() => setReview(null)} title={review?.decision === "approved" ? "Aprovar documento" : review?.decision === "rejected" ? "Solicitar correção do documento" : "Cancelar solicitação"} description={review?.decision === "cancelled" ? "O pedido será encerrado e seu histórico preservado." : "Registre a conclusão da revisão. O documento original será preservado."} pending={action.pending} onSave={(reason) => review ? action.run(() => review.decision === "cancelled" ? cancelLegalDocumentRequest(review.request.id, reason) : reviewLegalDocumentRequest(review.request.id, review.decision, reason), "Solicitação atualizada") : Promise.resolve(false)} />
  </OperationPanel>;
}
