import { useState, type FormEvent } from "react";
import { useQuery } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { listLegalAppointments, listLegalCaseTasks, listLegalTaskTemplates, saveLegalAppointment, saveLegalCaseTask, saveLegalTaskTemplate } from "@/lib/api/legal-operations";
import type { LegalAppointment, LegalAppointmentPayload, LegalAppointmentType, LegalCaseTask, LegalTaskPayload, LegalTaskTemplate } from "@/types/legal-operations";
import { LegalField } from "../LegalShared";
import { legalDate, localDateTime, selectClassName, useLegalAction } from "../legal-ui";
import { OperationPanel, OperationReasonDialog, OperationRecords, ProviderNotConfigured } from "./OperationPanel";
import { operationsKey, type LegalOperationsProps } from "./operations-ui";

const APPOINTMENT_TYPES = { consultation: "Consulta", hearing: "Audiência", diligence: "Diligência", meeting: "Reunião" } as const;
const TASK_STATUS = { open: "Em aberto", completed: "Concluída", cancelled: "Cancelada" } as const;
const APPOINTMENT_STATUS = { scheduled: "Agendado", completed: "Realizado", cancelled: "Cancelado" } as const;
function taskPayload(task: LegalCaseTask): LegalTaskPayload { return { title: task.title, notes: task.notes, template_id: task.template_id, assignee_id: task.assignee_id, substitute_id: task.substitute_id, due_at: task.due_at, status: task.status, cancellation_reason: task.cancellation_reason }; }
function appointmentPayload(event: LegalAppointment): LegalAppointmentPayload { return { title: event.title, appointment_type: event.appointment_type, starts_at: event.starts_at, ends_at: event.ends_at, location: event.location, notes: event.notes, assignee_id: event.assignee_id, substitute_id: event.substitute_id, status: event.status, cancellation_reason: event.cancellation_reason }; }

function Assignments({ props, assignee, substitute, onAssignee, onSubstitute }: { props: LegalOperationsProps; assignee: string; substitute: string; onAssignee: (id: string) => void; onSubstitute: (id: string) => void }) {
  const allowed = new Set([props.legalCase.owner_id, ...(props.members ?? []).map((member) => member.profile_id)]);
  const collaborators = props.workspace.collaborators.filter((person) => allowed.has(person.id));
  return <div className="grid gap-3 sm:grid-cols-2"><LegalField label="Responsável">{(id) => <select id={id} className={selectClassName} required value={assignee} onChange={(event) => { onAssignee(event.target.value); if (event.target.value === substitute) onSubstitute(""); }}><option value="">Selecione</option>{collaborators.map((person) => <option key={person.id} value={person.id}>{person.nome}</option>)}</select>}</LegalField><LegalField label="Substituto (opcional)">{(id) => <select id={id} className={selectClassName} value={substitute} onChange={(event) => onSubstitute(event.target.value)}><option value="">Sem substituto</option>{collaborators.filter((person) => person.id !== assignee).map((person) => <option key={person.id} value={person.id}>{person.nome}</option>)}</select>}</LegalField></div>;
}

function TaskDialog({ props, task, templates, onClose }: { props: LegalOperationsProps; task?: LegalCaseTask; templates: LegalTaskTemplate[]; onClose: () => void }) {
  const [title, setTitle] = useState(task?.title ?? "");
  const [notes, setNotes] = useState(task?.notes ?? "");
  const [due, setDue] = useState(localDateTime(task?.due_at));
  const [assignee, setAssignee] = useState(task?.assignee_id ?? props.legalCase.owner_id);
  const [substitute, setSubstitute] = useState(task?.substitute_id ?? "");
  const [templateId, setTemplateId] = useState(task?.template_id ?? "");
  const action = useLegalAction();
  function applyTemplate(id: string) { setTemplateId(id); const template = templates.find((item) => item.id === id); if (!template) return; setTitle(template.title); setNotes(template.notes); if (template.default_due_days != null) { const date = new Date(); date.setDate(date.getDate() + template.default_due_days); setDue(localDateTime(date.toISOString())); } }
  async function save(event: FormEvent) { event.preventDefault(); if (await action.run(() => saveLegalCaseTask(props.legalCase.id, { title: title.trim(), notes: notes.trim(), template_id: templateId || null, assignee_id: assignee, substitute_id: substitute || null, due_at: due ? new Date(due).toISOString() : null, status: task?.status ?? "open" }, task?.id), task ? "Tarefa atualizada" : "Tarefa criada")) onClose(); }
  return <Dialog open onOpenChange={(value) => { if (!value && !action.pending) onClose(); }}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>{task ? "Editar tarefa jurídica" : "Nova tarefa jurídica"}</DialogTitle><DialogDescription>Defina quem executa e quem substitui entre os participantes deste caso.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={(event) => void save(event)}>{!task && templates.length ? <LegalField label="Aplicar modelo de tarefa">{(id) => <select id={id} className={selectClassName} value={templateId} onChange={(event) => applyTemplate(event.target.value)}><option value="">Criar sem modelo</option>{templates.map((template) => <option key={template.id} value={template.id}>{template.title}</option>)}</select>}</LegalField> : null}<LegalField label="Título da tarefa">{(id) => <Input id={id} required maxLength={150} value={title} onChange={(event) => setTitle(event.target.value)} />}</LegalField><Assignments props={props} assignee={assignee} substitute={substitute} onAssignee={setAssignee} onSubstitute={setSubstitute} /><LegalField label="Data de acompanhamento">{(id) => <Input id={id} type="datetime-local" value={due} onChange={(event) => setDue(event.target.value)} />}</LegalField><LegalField label="Orientação da tarefa" hint="Use orientações operacionais. Dados médicos e fiscais ficam nos documentos e entrevistas restritos.">{(id) => <Textarea id={id} maxLength={1000} value={notes} onChange={(event) => setNotes(event.target.value)} />}</LegalField><DialogFooter><Button type="button" variant="outline" onClick={onClose}>Cancelar</Button><Button type="submit" disabled={action.pending || !title.trim() || !assignee}>Salvar tarefa</Button></DialogFooter></form></DialogContent></Dialog>;
}

function AppointmentDialog({ props, appointment, onClose }: { props: LegalOperationsProps; appointment?: LegalAppointment; onClose: () => void }) {
  const [title, setTitle] = useState(appointment?.title ?? "");
  const [type, setType] = useState<LegalAppointmentType>(appointment?.appointment_type ?? "consultation");
  const [start, setStart] = useState(localDateTime(appointment?.starts_at));
  const [end, setEnd] = useState(localDateTime(appointment?.ends_at));
  const [location, setLocation] = useState(appointment?.location ?? "");
  const [notes, setNotes] = useState(appointment?.notes ?? "");
  const [assignee, setAssignee] = useState(appointment?.assignee_id ?? props.legalCase.owner_id);
  const [substitute, setSubstitute] = useState(appointment?.substitute_id ?? "");
  const action = useLegalAction();
  async function save(event: FormEvent) { event.preventDefault(); if (await action.run(() => saveLegalAppointment(props.legalCase.id, { title: title.trim(), appointment_type: type, starts_at: new Date(start).toISOString(), ends_at: new Date(end).toISOString(), location: location.trim(), notes: notes.trim(), assignee_id: assignee, substitute_id: substitute || null, status: appointment?.status ?? "scheduled" }, appointment?.id), appointment ? "Compromisso atualizado" : "Compromisso agendado internamente")) onClose(); }
  return <Dialog open onOpenChange={(value) => { if (!value && !action.pending) onClose(); }}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{appointment ? "Editar compromisso" : "Novo compromisso jurídico"}</DialogTitle><DialogDescription>O compromisso ficará na agenda interna deste caso.</DialogDescription></DialogHeader><form onSubmit={(event) => void save(event)} className="space-y-4"><LegalField label="Título do compromisso">{(id) => <Input id={id} required maxLength={150} value={title} onChange={(event) => setTitle(event.target.value)} />}</LegalField><LegalField label="Tipo de compromisso">{(id) => <select id={id} className={selectClassName} value={type} onChange={(event) => setType(event.target.value as LegalAppointmentType)}>{Object.entries(APPOINTMENT_TYPES).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select>}</LegalField><div className="grid gap-3 sm:grid-cols-2"><LegalField label="Início">{(id) => <Input id={id} type="datetime-local" required value={start} onChange={(event) => setStart(event.target.value)} />}</LegalField><LegalField label="Fim">{(id) => <Input id={id} type="datetime-local" required min={start || undefined} value={end} onChange={(event) => setEnd(event.target.value)} />}</LegalField></div><Assignments props={props} assignee={assignee} substitute={substitute} onAssignee={setAssignee} onSubstitute={setSubstitute} /><LegalField label="Local ou sala">{(id) => <Input id={id} maxLength={200} value={location} onChange={(event) => setLocation(event.target.value)} />}</LegalField><LegalField label="Orientação operacional" hint="Registre apenas orientações de participação, sem dados médicos ou fiscais.">{(id) => <Textarea id={id} maxLength={1000} value={notes} onChange={(event) => setNotes(event.target.value)} />}</LegalField><DialogFooter><Button type="button" variant="outline" onClick={onClose}>Cancelar</Button><Button type="submit" disabled={action.pending || !title.trim() || !assignee || !start || !end || new Date(end) <= new Date(start)}>Salvar compromisso</Button></DialogFooter></form></DialogContent></Dialog>;
}

function TaskTemplateDialog({ onClose }: { onClose: () => void }) {
  const [title, setTitle] = useState(""); const [notes, setNotes] = useState(""); const [days, setDays] = useState(""); const action = useLegalAction();
  return <Dialog open onOpenChange={(value) => { if (!value && !action.pending) onClose(); }}><DialogContent><DialogHeader><DialogTitle>Novo modelo de tarefa</DialogTitle><DialogDescription>Modelo reutilizável do escritório, sem dados de clientes.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); void action.run(() => saveLegalTaskTemplate({ title: title.trim(), notes: notes.trim(), default_due_days: days ? Number(days) : null }), "Modelo de tarefa criado").then((saved) => { if (saved) onClose(); }); }}><LegalField label="Nome do modelo">{(id) => <Input id={id} required maxLength={150} value={title} onChange={(event) => setTitle(event.target.value)} />}</LegalField><LegalField label="Instruções do modelo">{(id) => <Textarea id={id} maxLength={1000} value={notes} onChange={(event) => setNotes(event.target.value)} />}</LegalField><LegalField label="Dias para acompanhamento" hint="Contagem interna em dias corridos, sem cálculo de prazo processual.">{(id) => <Input id={id} type="number" min={0} max={365} value={days} onChange={(event) => setDays(event.target.value)} />}</LegalField><DialogFooter><Button type="button" variant="outline" onClick={onClose}>Cancelar</Button><Button type="submit" disabled={action.pending || !title.trim()}>Salvar modelo</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function LegalCaseWork(props: LegalOperationsProps) {
  const tasks = useQuery({ queryKey: operationsKey(props, "tasks"), queryFn: () => listLegalCaseTasks(props.legalCase.id) });
  const appointments = useQuery({ queryKey: operationsKey(props, "appointments"), queryFn: () => listLegalAppointments(props.legalCase.id) });
  const templates = useQuery({ queryKey: ["legal", props.workspace.user_id, props.workspace.tenant_id, "task-templates"], queryFn: listLegalTaskTemplates });
  const [taskForm, setTaskForm] = useState<LegalCaseTask | "new" | null>(null);
  const [appointmentForm, setAppointmentForm] = useState<LegalAppointment | "new" | null>(null);
  const [templateForm, setTemplateForm] = useState(false);
  const [cancel, setCancel] = useState<{ task?: LegalCaseTask; appointment?: LegalAppointment } | null>(null);
  const action = useLegalAction();
  const name = (id?: string | null) => props.workspace.collaborators.find((person) => person.id === id)?.nome ?? "Participante do caso";
  return <div className="space-y-4"><OperationPanel title="Tarefas do caso" description="Distribua o trabalho entre responsáveis e substitutos com acompanhamento próprio." actions={props.canEdit ? <div className="flex flex-wrap gap-2">{props.workspace.can_create ? <Button size="sm" variant="outline" onClick={() => setTemplateForm(true)}>Novo modelo</Button> : null}<Button size="sm" onClick={() => setTaskForm("new")}>Nova tarefa</Button></div> : null}><OperationRecords pending={tasks.isPending} error={tasks.error} retry={() => void tasks.refetch()} empty="Nenhuma tarefa cadastrada" count={tasks.data?.length ?? 0}>{tasks.data?.map((task) => <div key={task.id} className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><p className="break-words font-medium">{task.title}</p><Badge variant="secondary">{TASK_STATUS[task.status]}</Badge></div><p className="text-xs text-muted-foreground">Responsável: {name(task.assignee_id)}{task.substitute_id ? ` · Substituto: ${name(task.substitute_id)}` : ""}{task.due_at ? ` · ${legalDate(task.due_at, true)}` : ""}</p>{task.notes ? <p className="whitespace-pre-wrap break-words text-sm">{task.notes}</p> : null}{task.cancellation_reason ? <p className="text-sm text-muted-foreground">Cancelamento: {task.cancellation_reason}</p> : null}{props.canEdit && task.status === "open" ? <div className="flex flex-wrap gap-2"><Button size="sm" disabled={action.pending} onClick={() => void action.run(() => saveLegalCaseTask(props.legalCase.id, { ...taskPayload(task), status: "completed" }, task.id), "Tarefa concluída")}>Concluir tarefa</Button><Button size="sm" variant="outline" onClick={() => setTaskForm(task)}>Editar tarefa</Button><Button size="sm" variant="ghost" onClick={() => setCancel({ task })}>Cancelar tarefa</Button></div> : null}</div>)}</OperationRecords></OperationPanel>
    <OperationPanel title="Agenda jurídica do caso" description="Consultas, audiências e diligências com registro de realização e cancelamento." actions={props.canEdit ? <Button size="sm" onClick={() => setAppointmentForm("new")}>Novo compromisso</Button> : null}><ProviderNotConfigured provider="Google Calendar">Os compromissos são mantidos nesta agenda interna. A sincronização externa depende da conexão e homologação do calendário do escritório.</ProviderNotConfigured><OperationRecords pending={appointments.isPending} error={appointments.error} retry={() => void appointments.refetch()} empty="Nenhum compromisso agendado" count={appointments.data?.length ?? 0}>{appointments.data?.map((appointment) => <div key={appointment.id} className="space-y-3 rounded-lg border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><p className="break-words font-medium">{appointment.title}</p><Badge variant="secondary">{APPOINTMENT_STATUS[appointment.status]}</Badge></div><p className="text-sm">{APPOINTMENT_TYPES[appointment.appointment_type]} · {legalDate(appointment.starts_at, true)} até {legalDate(appointment.ends_at, true)}</p><p className="text-xs text-muted-foreground">Responsável: {name(appointment.assignee_id)}{appointment.substitute_id ? ` · Substituto: ${name(appointment.substitute_id)}` : ""}</p>{appointment.location ? <p className="break-words text-sm">Local: {appointment.location}</p> : null}{appointment.notes ? <p className="whitespace-pre-wrap break-words text-sm">{appointment.notes}</p> : null}{appointment.cancellation_reason ? <p className="text-sm text-muted-foreground">Cancelamento: {appointment.cancellation_reason}</p> : null}{props.canEdit && appointment.status === "scheduled" ? <div className="flex flex-wrap gap-2"><Button size="sm" disabled={action.pending} onClick={() => void action.run(() => saveLegalAppointment(props.legalCase.id, { ...appointmentPayload(appointment), status: "completed" }, appointment.id), "Realização registrada")}>Marcar como realizado</Button><Button size="sm" variant="outline" onClick={() => setAppointmentForm(appointment)}>Editar compromisso</Button><Button size="sm" variant="ghost" onClick={() => setCancel({ appointment })}>Cancelar compromisso</Button></div> : null}</div>)}</OperationRecords></OperationPanel>
    {taskForm ? <TaskDialog props={props} task={taskForm === "new" ? undefined : taskForm} templates={templates.data ?? []} onClose={() => setTaskForm(null)} /> : null}{appointmentForm ? <AppointmentDialog props={props} appointment={appointmentForm === "new" ? undefined : appointmentForm} onClose={() => setAppointmentForm(null)} /> : null}{templateForm ? <TaskTemplateDialog onClose={() => setTemplateForm(false)} /> : null}
    <OperationReasonDialog key={cancel?.task?.id ?? cancel?.appointment?.id} open={Boolean(cancel)} onClose={() => setCancel(null)} title={cancel?.task ? "Cancelar tarefa" : "Cancelar compromisso"} description="Registre o motivo. O item e seu histórico permanecerão disponíveis no caso." pending={action.pending} actionLabel="Confirmar cancelamento" onSave={(reason) => action.run(() => cancel?.task ? saveLegalCaseTask(props.legalCase.id, { ...taskPayload(cancel.task), status: "cancelled", cancellation_reason: reason }, cancel.task.id) : cancel?.appointment ? saveLegalAppointment(props.legalCase.id, { ...appointmentPayload(cancel.appointment), status: "cancelled", cancellation_reason: reason }, cancel.appointment.id) : Promise.resolve(), "Cancelamento registrado")} />
  </div>;
}
