import { financeRpc } from "@/lib/api/legal-case-finance";
import type { CaseFinancialData, FinanceReferences } from "@/types/legal-case-finance";
import { OperationPanel } from "../operations/OperationPanel";
import { coefficient } from "../ir/financial/financial-ui";
import { FinanceForm, FinanceRecord } from "./FinanceShared";
import { canonicalMoney, money, noteField, options, type FinanceField } from "./finance-ui";
export default function FinanceAgreements({ caseId, data, references, owner, canEdit }: { caseId: string; data: CaseFinancialData; references: FinanceReferences; owner: boolean; canEdit: boolean }) {
  const documents = references.documents.map((d) => ({ value: d.id, label: d.display_name }));
  const contractVersions = references.contracts.flatMap((contract) => contract.versions.filter((v) => v.status === "approved" && !v.superseded_at).map((v) => ({ value: v.id, label: `${contract.title} · versão ${v.version_number}` })));
  const baseOptions = { manual: "Documento e valor conferidos", ir_recovery: "Recebimento efetivo registrado no IR", ir_decision: "Decisão documental registrada no IR" };
  const fields: FinanceField[] = [
    { key: "instrument_version_id", label: "Contrato aprovado", kind: "select", options: contractVersions }, { key: "agreement_key", label: "Referência do acordo", hint: "Use a mesma referência para revisar as condições deste acordo; ex.: honorários-principais." },
    { key: "title", label: "Título das condições" }, { key: "model", label: "Modelo contratado", kind: "select", initial: "fixed", options: options({ fixed: "Valor fixo", success: "Percentual de êxito" }) },
    { key: "fixed_amount", label: "Honorários fixos (R$)", kind: "money", when: (v) => v.model === "fixed" },
    { key: "success_rate", label: "Percentual em fração decimal", hint: "Exemplo: 0,20 corresponde a 20%. Até nove casas decimais.", when: (v) => v.model === "success" },
    { key: "basis_kind", label: "Origem da base de êxito", kind: "select", initial: "manual", options: options(baseOptions), when: (v) => v.model === "success" },
    { key: "trigger_description", label: "Condição para os honorários serem devidos", kind: "textarea" }, { key: "exclusions", label: "Exclusões previstas no contrato", kind: "textarea", required: false },
  ];
  return <OperationPanel title="Honorários contratuais" description="Condições vinculadas à versão aprovada do contrato. A evidência de aceite, a base e as parcelas passam por revisão antes de qualquer cobrança.">
    {canEdit ? <FinanceForm title="Definir condições de honorários" fields={fields} onSave={(v) => financeRpc("legal_create_fee_agreement", { p_case_id: caseId, p_payload: { ...v, fixed_amount: v.model === "fixed" ? canonicalMoney(v.fixed_amount) : "0.00", success_rate: v.model === "success" ? coefficient(v.success_rate) : "0", basis_kind: v.model === "fixed" ? "manual" : v.basis_kind } })} /> : null}
    {!data.agreements.length ? <p className="text-sm text-muted-foreground">Nenhuma condição de honorários registrada. Prepare o contrato em Atendimento e trabalho.</p> : null}
    {data.agreements.map((agreement) => <FinanceRecord key={agreement.id} title={`${agreement.title} · versão ${agreement.version_number}${agreement.superseded_at ? " · substituída" : ""}`} status={agreement.status}>
      <p className="text-sm">{agreement.model === "fixed" ? money(agreement.fixed_amount) : `Fração contratada: ${agreement.success_rate} · ${baseOptions[agreement.basis_kind]}`}</p><p className="whitespace-pre-wrap break-words text-sm">{agreement.trigger_description}</p>{agreement.exclusions ? <p className="text-sm text-muted-foreground">Exclusões: {agreement.exclusions}</p> : null}
      {owner && agreement.status === "draft" ? <FinanceForm title="Revisar condições" button="Registrar revisão" fields={[{ key: "decision", label: "Decisão", kind: "select", options: options({ approved: "Aprovar", rejected: "Não aprovar" }) }, { key: "acceptance", label: "Evidência de aceite do contrato", kind: "select", options: references.signatures.filter((s) => s.version_id === agreement.instrument_version_id).map((s) => ({ value: s.id, label: `${documents.find((d) => d.value === s.document_id)?.label ?? "Evidência registrada"} · ${new Date(s.created_at).toLocaleDateString("pt-BR")}` })), when: (v) => v.decision === "approved" }, noteField]} onSave={(v) => financeRpc("legal_review_fee_agreement", { p_version_id: agreement.id, p_decision: v.decision, p_note: v.note, p_acceptance_record_id: v.decision === "approved" ? v.acceptance : null })} /> : null}
      {owner && agreement.status === "approved" && !agreement.superseded_at ? <FinanceForm title="Preparar base dos honorários" description="O sistema conserva os valores e as fontes conferidas. Parcelas da mesma base não podem superar o honorário aprovado." fields={[
        { key: "title", label: "Identificação desta base" },
        ...(agreement.basis_kind === "manual" ? [{ key: "document_id", label: "Documento que comprova a base", kind: "select" as const, options: documents }, { key: "proof_line", label: "Página ou linha da prova", initial: "1" }, { key: "base_amount", label: "Valor documental da base (R$)", kind: "money" as const }] : [{ key: "source_id", label: agreement.basis_kind === "ir_recovery" ? "Recebimento comprovado no IR" : "Pedido com decisão documental", kind: "select" as const, options: agreement.basis_kind === "ir_recovery" ? references.recoveries.map((r) => ({ value: r.id, label: `${r.received_on} · ${money(r.amount)}` })) : references.claims.map((c) => ({ value: c.id, label: c.title })) }]),
        { key: "deductions", label: "Deduções contratuais da base (R$)", kind: "money", initial: "0,00", when: () => agreement.model === "success" },
        { key: "supersedes_basis_id", label: "Substituir base aprovada sem parcelas ativas", kind: "select", required: false, options: data.bases.filter((b) => b.agreement_id === agreement.id && b.status === "approved" && !b.superseded_at).map((b) => ({ value: b.id, label: b.title })) },
        { key: "justification", label: "Conferência das fontes e das condições de êxito", kind: "textarea" },
      ]} onSave={(v) => financeRpc("legal_create_fee_basis", { p_agreement_id: agreement.id, p_payload: { title: v.title, source_ids: agreement.basis_kind === "manual" ? [] : [v.source_id], ...(agreement.basis_kind === "manual" ? { document_id: v.document_id, proof_line: v.proof_line, base_amount: canonicalMoney(v.base_amount) } : {}), deductions: agreement.model === "fixed" ? "0.00" : canonicalMoney(v.deductions), justification: v.justification, supersedes_basis_id: v.supersedes_basis_id || null } })} /> : null}
      {data.bases.filter((b) => b.agreement_id === agreement.id).map((base) => <FinanceRecord key={base.id} title={`${base.title}${base.superseded_at ? " · substituída" : ""}`} status={base.status}><p className="text-sm">Base {money(base.base_amount)} · deduções {money(base.deductions)} · honorários {money(base.fee_amount)}</p>{owner && base.status === "draft" ? <FinanceForm title="Conferir base" button="Salvar conferência" fields={[{ key: "decision", label: "Decisão", kind: "select", options: options({ approved: "Aprovar base", rejected: "Não aprovar" }) }, noteField]} onSave={(v) => financeRpc("legal_review_fee_basis", { p_basis_id: base.id, p_decision: v.decision, p_note: v.note })} /> : null}</FinanceRecord>)}
    </FinanceRecord>)}
  </OperationPanel>;
}
