import { financeRpc } from "@/lib/api/legal-case-finance";
import type { CaseFinancialData, FinanceReferences } from "@/types/legal-case-finance";
import { OperationPanel } from "../operations/OperationPanel";
import { FinanceForm, FinanceRecord } from "./FinanceShared";
import { canonicalMoney, CATEGORIES, money, noteField, options, OWNERS, today, type FinanceField } from "./finance-ui";
export default function FinanceCash({ caseId, data, references, owner, canEdit }: { caseId: string; data: CaseFinancialData; references: FinanceReferences; owner: boolean; canEdit: boolean }) {
  const documents = references.documents.map((d) => ({ value: d.id, label: d.display_name }));
  const obligationOptions = data.obligations.filter((o) => o.status === "approved").map((o) => ({ value: o.id, label: `${o.title} · ${money(o.amount)}` }));
  const balanceById = new Map(data.context.obligations.map((o) => [o.id, o]));
  const transactionById = new Map(data.transactions.map((t) => [t.id, t]));
  const compensation = (v: Record<string, string>) => !v.reverses_id && v.from_owner === "client" && v.to_owner === "office";
  const cashFields: FinanceField[] = [
    { key: "reverses_id", label: "Este movimento estorna outro registro?", kind: "select", required: false, hint: "Deixe vazio para uma nova entrada ou saída. O estorno mantém o registro original.", options: data.transactions.filter((t) => !t.reverses_id).map((t) => ({ value: t.id, label: `${t.reference} · ${money(t.amount)} · ${OWNERS[t.from_owner]} → ${OWNERS[t.to_owner]}` })) },
    { key: "from_owner", label: "Origem do dinheiro", kind: "select", options: options(OWNERS), when: (v) => !v.reverses_id }, { key: "to_owner", label: "Destino do dinheiro", kind: "select", options: options(OWNERS), when: (v) => !v.reverses_id },
    { key: "amount", label: "Valor efetivo (R$)", kind: "money", hint: "Somente o valor comprovado. Tarifas devem ser conferidas separadamente." }, { key: "occurred_on", label: "Data do movimento comprovado", kind: "date", initial: today() },
    { key: "document_id", label: "Comprovante do movimento ou autorização de compensação", kind: "select", options: documents }, { key: "proof_line", label: "Página, linha ou identificação no comprovante" },
    { key: "reference", label: "Referência única para conciliação", hint: "Ex.: identificação do extrato. Não pode identificar outro movimento deste escritório." }, { key: "reason", label: "Conferência do movimento e da titularidade", kind: "textarea" },
    { key: "transfer_obligation_id", label: "Honorário aprovado para compensação", kind: "select", options: data.obligations.filter((o) => o.category === "fee" && o.status === "approved").map((o) => ({ value: o.id, label: o.title })), when: compensation },
    { key: "compensation_authorized", label: "Conferi a autorização documental do cliente para compensar estes honorários", kind: "checkbox", when: compensation },
    ...data.allocations.filter((a) => a.kind === "settlement").map((allocation): FinanceField => ({ key: `refund_${allocation.id}`, label: `Parcela do estorno: ${data.obligations.find((o) => o.id === allocation.obligation_id)?.title ?? "Obrigação"}`, kind: "money", initial: "0,00", hint: `Alocação original de ${money(allocation.amount)}. Informe quanto deste estorno reabre a obrigação.`, when: (v) => v.reverses_id === allocation.cash_transaction_id && !transactionById.get(v.reverses_id)?.transfer_obligation_id })),
  ];
  return <div className="space-y-4"><OperationPanel title="Valores a receber e a pagar" description="Honorários, custas, reembolsos, adiantamentos e repasses conservam a titularidade dos recursos. A aprovação não registra pagamento.">
    {canEdit ? <FinanceForm title="Criar obrigação ou parcela" fields={[
      { key: "title", label: "Descrição" }, { key: "category", label: "Natureza", kind: "select", options: options(CATEGORIES) },
      { key: "direction", label: "Movimento esperado", kind: "select", options: options({ receivable: "A receber", payable: "A pagar" }), when: (v) => !["fee", "advance", "client_transfer"].includes(v.category) },
      { key: "funds_owner", label: "A quem pertence o recurso", kind: "select", options: options({ client: "Cliente", office: "Escritório" }), when: (v) => !["fee", "advance", "client_transfer"].includes(v.category) },
      { key: "beneficiary", label: "Beneficiário", kind: "select", options: options({ office: "Escritório", client: "Cliente", third_party: "Terceiro" }), when: (v) => !["fee", "advance", "client_transfer"].includes(v.category) },
      { key: "amount", label: "Valor desta obrigação (R$)", kind: "money" }, { key: "due_on", label: "Vencimento", kind: "date", initial: today() },
      { key: "basis_id", label: "Base de honorários aprovada", kind: "select", options: data.bases.filter((b) => b.status === "approved" && !b.superseded_at).map((b) => ({ value: b.id, label: `${b.title} · honorários ${money(b.fee_amount)}` })), when: (v) => v.category === "fee" },
      { key: "document_id", label: "Documento que fundamenta a obrigação", kind: "select", options: documents, when: (v) => v.category !== "fee" }, { key: "notes", label: "Observações internas", kind: "textarea", required: false },
    ]} onSave={(v) => { const basis = data.bases.find((b) => b.id === v.basis_id); return financeRpc("legal_create_financial_obligation", { p_case_id: caseId, p_payload: { title: v.title, category: v.category, amount: canonicalMoney(v.amount), due_on: v.due_on, notes: v.notes, direction: v.category === "client_transfer" ? "payable" : ["fee", "advance"].includes(v.category) ? "receivable" : v.direction, funds_owner: v.category === "fee" ? "office" : ["advance", "client_transfer"].includes(v.category) ? "client" : v.funds_owner, beneficiary: v.category === "fee" || v.category === "advance" ? "office" : v.category === "client_transfer" ? "client" : v.beneficiary, ...(v.category === "fee" ? { basis_id: basis?.id, agreement_id: basis?.agreement_id } : { document_id: v.document_id }) } }); }} /> : null}
    {data.obligations.map((obligation) => <FinanceRecord key={obligation.id} title={obligation.title} status={obligation.status}><p className="text-sm">{CATEGORIES[obligation.category]} · {obligation.direction === "receivable" ? "a receber" : "a pagar"} · {OWNERS[obligation.funds_owner]} · vencimento {obligation.due_on}</p><p className="text-sm">Total {money(obligation.amount)} · conciliado {money(balanceById.get(obligation.id)?.paid)} · restante {money(balanceById.get(obligation.id)?.remaining)}</p>{owner && obligation.status === "draft" ? <FinanceForm title="Aprovar obrigação" fields={[noteField]} button="Aprovar" onSave={(v) => financeRpc("legal_review_financial_obligation", { p_obligation_id: obligation.id, p_note: v.note })} /> : null}{owner && obligation.status !== "cancelled" && balanceById.get(obligation.id)?.paid === "0.00" ? <FinanceForm title="Cancelar obrigação sem baixa" fields={[noteField]} button="Registrar cancelamento" onSave={(v) => financeRpc("legal_cancel_financial_obligation", { p_obligation_id: obligation.id, p_reason: v.note })} /> : null}</FinanceRecord>)}
  </OperationPanel><OperationPanel title="Movimentos e conciliação" description="Registre somente recursos comprovados sob custódia do escritório. Este livro não realiza transferência bancária. Recebimentos de IR diretamente pelo cliente não entram automaticamente aqui.">
    {owner ? <FinanceForm title="Registrar movimento ou estorno" button="Confirmar movimento comprovado" description="Estornos exigem nova prova. Se o movimento original quitou obrigações, indique quais valores devem voltar a ficar em aberto. Compensações exigem autorização documental e são conciliadas na mesma operação." fields={cashFields} onSave={(v, context) => { const original = transactionById.get(v.reverses_id); return financeRpc("legal_record_cash_transaction", { p_case_id: caseId, p_payload: { from_owner: original?.to_owner ?? v.from_owner, to_owner: original?.from_owner ?? v.to_owner, amount: canonicalMoney(v.amount), occurred_on: v.occurred_on, document_id: v.document_id, proof_line: v.proof_line, reference: v.reference, reason: v.reason, reverses_id: original?.id ?? null, transfer_obligation_id: original?.transfer_obligation_id ?? (compensation(v) ? v.transfer_obligation_id : null), compensation_authorized: compensation(v) && v.compensation_authorized === "true", idempotency_key: context.idempotencyKey, allocation_reversals: original && !original.transfer_obligation_id ? data.allocations.filter((a) => a.cash_transaction_id === original.id && a.kind === "settlement").map((a) => ({ allocation_id: a.id, amount: canonicalMoney(v[`refund_${a.id}`] || "0,00") })).filter((a) => a.amount !== "0.00") : [] } }); }} /> : null}
    {[...data.transactions].sort((a, b) => b.created_at.localeCompare(a.created_at)).map((transaction) => <FinanceRecord key={transaction.id} title={`${transaction.reference} · ${money(transaction.amount)}`}><p className="text-sm">{transaction.occurred_on} · {OWNERS[transaction.from_owner]} → {OWNERS[transaction.to_owner]}{transaction.reverses_id ? " · estorno vinculado" : ""}</p><p className="break-words text-sm text-muted-foreground">{transaction.reason}</p><ul className="space-y-1 text-sm">{data.allocations.filter((a) => a.cash_transaction_id === transaction.id).map((a) => <li key={a.id}>{a.kind === "refund" ? "Reabre" : "Concilia"} {data.obligations.find((o) => o.id === a.obligation_id)?.title ?? "Obrigação"}: {money(a.amount)}</li>)}</ul>{owner && !transaction.reverses_id && !transaction.transfer_obligation_id && data.context.transactions.find((t) => t.id === transaction.id)?.unallocated !== "0.00" ? <FinanceForm title="Conciliar com uma obrigação" button="Registrar conciliação" fields={[{ key: "obligation_id", label: "Obrigação aprovada", kind: "select", options: obligationOptions }, { key: "amount", label: "Valor desta conciliação (R$)", kind: "money" }, noteField]} onSave={(v, context) => financeRpc("legal_allocate_cash_transaction", { p_transaction_id: transaction.id, p_obligation_id: v.obligation_id, p_amount: canonicalMoney(v.amount), p_idempotency_key: context.idempotencyKey, p_reason: v.note })} /> : null}</FinanceRecord>)}
  </OperationPanel></div>;
}
