export type MoneyOwner = "external" | "client" | "office";
export interface FinanceRow { id: string; case_id: string; tenant_id: string; created_at: string }
export interface FeeAgreement extends FinanceRow { agreement_key: string; version_number: number; instrument_version_id: string; acceptance_record_id: string | null; title: string; model: "fixed" | "success"; fixed_amount: string; success_rate: string; basis_kind: "manual" | "ir_recovery" | "ir_decision"; trigger_description: string; exclusions: string; status: "draft" | "approved" | "rejected"; superseded_at: string | null }
export interface FeeBasis extends FinanceRow { agreement_id: string; title: string; base_amount: string; deductions: string; effective_base: string; fee_amount: string; status: "draft" | "approved" | "rejected"; superseded_at: string | null; source_ids: string[]; snapshot: Record<string, unknown> }
export interface FinancialObligation extends FinanceRow { title: string; category: "fee" | "cost" | "reimbursement" | "advance" | "client_transfer"; direction: "receivable" | "payable"; funds_owner: "client" | "office"; beneficiary: "office" | "client" | "third_party"; amount: string; due_on: string; agreement_id: string | null; basis_id: string | null; status: "draft" | "approved" | "cancelled"; notes: string }
export interface CashTransaction extends FinanceRow { from_owner: MoneyOwner; to_owner: MoneyOwner; amount: string; occurred_on: string; reference: string; proof_line: string; document_id: string; reason: string; reverses_id: string | null; transfer_obligation_id: string | null }
export interface CashAllocation extends FinanceRow { cash_transaction_id: string; obligation_id: string; kind: "settlement" | "refund"; original_allocation_id: string | null; amount: string; reason: string }
export interface StatementSnapshot { currency: "BRL"; opening: { client: string; office: string }; closing: { client: string; office: string }; generated_at: string; obligations_basis: "current_at_generation"; movements: { id: string; date: string; from_owner: MoneyOwner; to_owner: MoneyOwner; amount: string; reference: string; reverses_id: string | null }[]; obligations: { id: string; title: string; category: string; direction: string; funds_owner: string; amount: string; paid: string; remaining: string; due_on: string }[] }
export interface FinancialStatement extends FinanceRow { title: string; version_number: number; period_start: string; period_end: string; public_note: string; status: "draft" | "approved" | "returned"; snapshot: StatementSnapshot }
export interface StatementRelease extends FinanceRow { statement_id: string; membership_id: string; expires_at: string; revoked_at: string | null }
export interface PaymentConnection { id: string; tenant_id: string; label: string; account_id: string; provider: "asaas"; environment: "sandbox" | "production"; status: "not_configured" | "ready" | "disabled" }
export interface ChargeAttempt extends FinanceRow { obligation_id: string; connection_id: string; amount: string; provider_customer_id: string; billing_type: "PIX" | "BOLETO" | "CREDIT_CARD"; due_on: string; status: "draft" | "approved" | "not_configured" | "sending" | "provider_accepted" | "unknown" | "failed" | "cancelled" | "reconciled"; provider_url: string | null; provider_charge_id: string | null }
export interface PaymentReceipt extends FinanceRow { charge_id: string; event_type: string; provider_event_id: string; amount: string | null; status: "needs_reconciliation" | "reconciled" | "ignored"; cash_transaction_id: string | null }
export interface CaseFinancialContext { client_balance: string; office_balance: string; obligations: { id: string; paid: string; remaining: string }[]; transactions: { id: string; unallocated: string; reversed: string }[] }
export interface CaseFinancialData { agreements: FeeAgreement[]; bases: FeeBasis[]; obligations: FinancialObligation[]; transactions: CashTransaction[]; allocations: CashAllocation[]; statements: FinancialStatement[]; releases: StatementRelease[]; connections: PaymentConnection[]; charges: ChargeAttempt[]; receipts: PaymentReceipt[]; context: CaseFinancialContext }
export interface FinanceReferences { documents: { id: string; display_name: string; category: string }[]; contracts: { id: string; title: string; versions: { id: string; version_number: number; status: string; superseded_at: string | null }[] }[]; signatures: { id: string; version_id: string; document_id: string; created_at: string }[]; recoveries: { id: string; amount: string; received_on: string }[]; claims: { id: string; title: string }[] }
