-- F6: immutable reviewed rule/calendar versions and case-bound assisted deadline proposals.
-- The pure deterministic engine is installed separately by migration 2350.
create table public.legal_deadline_calendar_versions(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id),calendar_key text not null check(length(btrim(calendar_key)) between 1 and 80),version_number integer not null check(version_number>0),title text not null check(length(btrim(title)) between 1 and 200),scope jsonb not null,timezone text not null check(length(timezone) between 1 and 100),valid_from date,valid_until date,body jsonb not null,sources jsonb not null default '[]',
 state text not null default 'draft' check(state in ('draft','approved','rejected','revoked')),created_by uuid not null references public.profiles(id),created_at timestamptz not null default clock_timestamp(),reviewed_by uuid references public.profiles(id),reviewed_at timestamptz,review_note text not null default '' check(length(review_note)<=4000),unique(tenant_id,calendar_key,version_number),unique(id,tenant_id),check(isfinite(valid_from) and isfinite(valid_until)),check(valid_until>=valid_from and valid_until-valid_from<=3660)
);
create table public.legal_deadline_rule_versions(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id),rule_key text not null check(length(btrim(rule_key)) between 1 and 80),version_number integer not null check(version_number>0),title text not null check(length(btrim(title)) between 1 and 200),scope jsonb not null,valid_from date,valid_until date,body jsonb not null,sources jsonb not null default '[]',
 state text not null default 'draft' check(state in ('draft','approved','rejected','revoked')),created_by uuid not null references public.profiles(id),created_at timestamptz not null default clock_timestamp(),reviewed_by uuid references public.profiles(id),reviewed_at timestamptz,review_note text not null default '' check(length(review_note)<=4000),unique(tenant_id,rule_key,version_number),unique(id,tenant_id),check(isfinite(valid_from) and isfinite(valid_until)),check(valid_until>=valid_from)
);
create table public.legal_deadline_versions(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null,case_id uuid not null,deadline_key text not null check(length(btrim(deadline_key)) between 1 and 80),version_number integer not null check(version_number>0),category text not null default 'restricted' check(category='restricted'),title text not null check(length(btrim(title)) between 1 and 200),proceeding_id uuid not null,inbox_id uuid,rule_version_id uuid,calendar_version_id uuid,input jsonb not null,snapshot jsonb not null,snapshot_hash text not null,result jsonb not null,engine_version text not null default 'legal-deadline-v1',
 state text not null default 'incomplete' check(state in ('incomplete','draft','in_review','reviewed','returned')),created_by uuid not null references public.profiles(id),created_at timestamptz not null default clock_timestamp(),reviewed_by uuid references public.profiles(id),reviewed_at timestamptz,review_note text not null default '' check(length(review_note)<=4000),task_id uuid,supersedes_version_id uuid,
 unique(case_id,deadline_key,version_number),unique(id,case_id,tenant_id),foreign key(case_id,tenant_id) references public.legal_cases(id,tenant_id),foreign key(proceeding_id,case_id,tenant_id) references public.judicial_proceedings(id,case_id,tenant_id),foreign key(inbox_id,case_id,tenant_id) references public.legal_judicial_inbox(id,case_id,tenant_id),foreign key(rule_version_id,tenant_id) references public.legal_deadline_rule_versions(id,tenant_id),foreign key(calendar_version_id,tenant_id) references public.legal_deadline_calendar_versions(id,tenant_id),foreign key(task_id,case_id,tenant_id) references public.legal_case_tasks(id,case_id,tenant_id),foreign key(supersedes_version_id,case_id,tenant_id) references public.legal_deadline_versions(id,case_id,tenant_id)
);
create index legal_deadline_case on public.legal_deadline_versions(case_id,created_at desc);
create table public.legal_deadline_reviews(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null,case_id uuid not null,version_id uuid not null,decision text not null check(decision in ('reviewed','returned')),snapshot_hash text not null,note text not null,reviewed_by uuid not null references public.profiles(id),created_at timestamptz not null default clock_timestamp(),foreign key(version_id,case_id,tenant_id) references public.legal_deadline_versions(id,case_id,tenant_id)
);
create or replace function public._legal_deadline_scope(p_scope jsonb,p_complete boolean default false) returns void language plpgsql immutable set search_path=pg_catalog,public,pg_temp as $$declare k text;begin
 perform public._legal_judicial_payload(p_scope,array['court','degree','unit','territory']);if octet_length(p_scope::text)>3000 then raise exception 'Bounded court scope required' using errcode='22023';end if;
 foreach k in array array['court','degree','unit','territory'] loop if (p_scope?k and (jsonb_typeof(p_scope->k)<>'string' or length(p_scope->>k)>200)) or (p_complete and coalesce(length(btrim(p_scope->>k)),0)=0) then raise exception 'Explicit complete court, degree, unit and territory scope required' using errcode='22023';end if;end loop;
end;$$;
create or replace function public._legal_deadline_sources(p_sources jsonb,p_tenant_id uuid,p_complete boolean default false) returns void language plpgsql security definer set search_path=pg_catalog,public,pg_temp as $$declare s jsonb;d public.legal_case_documents;checked date;begin
 if p_sources is null or jsonb_typeof(p_sources)<>'array' or jsonb_array_length(p_sources)>30 or (p_complete and jsonb_array_length(p_sources)=0) then raise exception 'Bounded documentary sources required' using errcode='22023';end if;
 for s in select value from jsonb_array_elements(p_sources) loop
  perform public._legal_judicial_payload(s,array['title','url','checked_on','version_note','document_id']);checked:=public._legal_judicial_date(s->>'checked_on');
  if coalesce(length(s->>'title'),0)>300 or coalesce(length(s->>'url'),0)>2000 or coalesce(length(s->>'version_note'),0)>1000 then raise exception 'Bounded source metadata required' using errcode='22023';end if;
  if s?'document_id' and nullif(s->>'document_id','') is not null then select * into d from public.legal_case_documents where id=(s->>'document_id')::uuid and tenant_id=p_tenant_id and category='general' and status='ready';if not found or not public.legal_can_access_case(d.case_id) then raise exception 'Accessible ready general source evidence required' using errcode='42501';end if;end if;
  if p_complete and (coalesce(length(btrim(s->>'title')),0)=0 or coalesce(s->>'url','') !~ '^https://[^[:space:]]+$' or checked is null or checked>public._ir4_today() or nullif(s->>'document_id','') is null) then raise exception 'Approval requires source title, official URL, checked date and documentary evidence' using errcode='22023';end if;
 end loop;
end;$$;
create or replace function public._legal_deadline_calendar_structure(p_body jsonb,p_complete boolean default false) returns void language plpgsql immutable set search_path=pg_catalog,public,pg_temp as $$declare e jsonb;k text;begin
 perform public._legal_judicial_payload(p_body,array['working_weekdays','exceptions','suspensions']);if octet_length(p_body::text)>500000 then raise exception 'Calendar body too large' using errcode='22023';end if;
 if jsonb_typeof(p_body->'working_weekdays') is distinct from 'array' or jsonb_array_length(p_body->'working_weekdays') not between 1 and 7 or exists(select 1 from jsonb_array_elements(p_body->'working_weekdays') x where x::text !~ '^[1-7]$') or (select count(distinct x) from jsonb_array_elements(p_body->'working_weekdays') x)<>jsonb_array_length(p_body->'working_weekdays') then raise exception 'Unique ISO weekdays 1..7 required' using errcode='22023';end if;
 if jsonb_typeof(p_body->'exceptions') is distinct from 'array' or jsonb_array_length(p_body->'exceptions')>1000 or jsonb_typeof(p_body->'suspensions') is distinct from 'array' or jsonb_array_length(p_body->'suspensions')>100 then raise exception 'Bounded exception and suspension arrays required' using errcode='22023';end if;
 for e in select value from jsonb_array_elements(p_body->'exceptions') loop
  perform public._legal_judicial_payload(e,array['on','working_day','suspend_count','allow_start','allow_due','reason','source_index']);if public._legal_judicial_date(e->>'on') is null then raise exception 'Exception civil date required' using errcode='22023';end if;
  foreach k in array array['suspend_count','allow_start','allow_due'] loop if jsonb_typeof(e->k) is distinct from 'boolean' then raise exception 'Explicit calendar effects required' using errcode='22023';end if;end loop;
  if e?'working_day' and jsonb_typeof(e->'working_day')<>'boolean' then raise exception 'Working day must be boolean' using errcode='22023';end if;
  if coalesce(length(btrim(e->>'reason')),0) not between 1 and 1000 or coalesce(e->>'source_index','') !~ '^[0-9]{1,2}$' then raise exception 'Exception reason and source index required' using errcode='22023';end if;
 end loop;
 if (select count(distinct value->>'on') from jsonb_array_elements(p_body->'exceptions'))<>jsonb_array_length(p_body->'exceptions') then raise exception 'Duplicate calendar date exceptions are ambiguous' using errcode='22023';end if;
 for e in select value from jsonb_array_elements(p_body->'suspensions') loop
  perform public._legal_judicial_payload(e,array['from','until','suspend_count','allow_start','allow_due','reason','source_index']);if public._legal_judicial_date(e->>'from') is null or public._legal_judicial_date(e->>'until') is null or (e->>'until')::date<(e->>'from')::date then raise exception 'Finite ordered suspension interval required' using errcode='22023';end if;
  foreach k in array array['suspend_count','allow_start','allow_due'] loop if jsonb_typeof(e->k) is distinct from 'boolean' then raise exception 'Explicit suspension effects required' using errcode='22023';end if;end loop;
  if coalesce(length(btrim(e->>'reason')),0) not between 1 and 1000 or coalesce(e->>'source_index','') !~ '^[0-9]{1,2}$' then raise exception 'Suspension reason and source index required' using errcode='22023';end if;
 end loop;
end;$$;
create or replace function public._legal_deadline_rule_structure(p_body jsonb,p_complete boolean default false) returns void language plpgsql immutable set search_path=pg_catalog,public,pg_temp as $$declare k text;begin
 perform public._legal_judicial_payload(p_body,array['regime','nature','modality','recipient_kind','conditions','exclusions','validity_note','transition_resolved','input_kind','anchor_kind','marker_offset_count','marker_offset_unit','marker_adjustment','exclude_marker','count_unit','apply_suspensions','due_adjustment','due_time']);if octet_length(p_body::text)>24000 then raise exception 'Rule body too large' using errcode='22023';end if;
 foreach k in array array['transition_resolved','exclude_marker','apply_suspensions'] loop if p_body?k and jsonb_typeof(p_body->k)<>'boolean' then raise exception 'Rule switches must be booleans' using errcode='22023';end if;end loop;
 if p_body?'marker_offset_count' and (jsonb_typeof(p_body->'marker_offset_count')<>'number' or p_body->>'marker_offset_count' !~ '^([0-9]|[1-5][0-9]|60)$') then raise exception 'Marker offset count must be integer 0..60' using errcode='22023';end if;
 if p_complete then
  foreach k in array array['regime','nature','modality','recipient_kind','conditions','exclusions','validity_note','anchor_kind'] loop if coalesce(length(btrim(p_body->>k)),0) not between 1 and 4000 then raise exception 'Rule scope, conditions, exclusions and validity must be explicit' using errcode='22023';end if;end loop;
  if not(p_body ?& array['regime','nature','modality','recipient_kind','conditions','exclusions','validity_note','transition_resolved','input_kind','anchor_kind','marker_offset_count','marker_offset_unit','marker_adjustment','exclude_marker','count_unit','apply_suspensions','due_adjustment','due_time']) or p_body->>'input_kind' not in ('civil_date','timestamp') or p_body->>'marker_offset_unit' not in ('business_days','calendar_days') or p_body->>'marker_adjustment' not in ('none','next_business_day') or p_body->>'count_unit' not in ('business_days','calendar_days') or p_body->>'due_adjustment' not in ('none','next_business_day') or coalesce(p_body->>'due_time','') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]$' then raise exception 'Explicit bounded rule operations, unit and local due time required' using errcode='22023';end if;
 end if;
end;$$;

create or replace function public.legal_deadline_create_calendar_version(p_payload jsonb) returns public.legal_deadline_calendar_versions language plpgsql security definer set search_path=pg_catalog,public,pg_temp as $$declare r public.legal_deadline_calendar_versions;t uuid:=public.legal_actual_tenant();begin
 if not public.legal_can_create() then raise exception 'Calendar catalog edit denied' using errcode='42501';end if;perform public._legal_judicial_payload(p_payload,array['calendar_key','title','scope','timezone','valid_from','valid_until','body','sources']);perform pg_advisory_xact_lock(hashtextextended('legal_judicial_catalog:'||t,0));if not public.legal_can_create() then raise exception 'Calendar catalog edit revoked' using errcode='42501';end if;
 r.id:=gen_random_uuid();r.tenant_id:=t;r.created_by:=auth.uid();r.created_at:=clock_timestamp();r.state:='draft';r.review_note:='';r.sources:='[]';r:=jsonb_populate_record(r,p_payload);r.valid_from:=public._legal_judicial_date(p_payload->>'valid_from');r.valid_until:=public._legal_judicial_date(p_payload->>'valid_until');
 perform public._legal_deadline_scope(r.scope);perform public._legal_deadline_calendar_structure(r.body);perform public._legal_deadline_sources(r.sources,t);
 if not exists(select 1 from pg_timezone_names where name=r.timezone) then raise exception 'Known IANA timezone required' using errcode='22023';end if;
 select coalesce(max(version_number),0)+1 into r.version_number from public.legal_deadline_calendar_versions where tenant_id=t and calendar_key=r.calendar_key;insert into public.legal_deadline_calendar_versions values(r.*) returning * into r;
 perform public._legal_judicial_event(t,null,'calendar_drafted',jsonb_build_object('version_id',r.id));return r;
end;$$;
create or replace function public.legal_deadline_create_rule_version(p_payload jsonb) returns public.legal_deadline_rule_versions language plpgsql security definer set search_path=pg_catalog,public,pg_temp as $$declare r public.legal_deadline_rule_versions;t uuid:=public.legal_actual_tenant();begin
 if not public.legal_can_create() then raise exception 'Rule catalog edit denied' using errcode='42501';end if;perform public._legal_judicial_payload(p_payload,array['rule_key','title','scope','valid_from','valid_until','body','sources']);perform pg_advisory_xact_lock(hashtextextended('legal_judicial_catalog:'||t,0));if not public.legal_can_create() then raise exception 'Rule catalog edit revoked' using errcode='42501';end if;
 r.id:=gen_random_uuid();r.tenant_id:=t;r.created_by:=auth.uid();r.created_at:=clock_timestamp();r.state:='draft';r.review_note:='';r.sources:='[]';r:=jsonb_populate_record(r,p_payload);r.valid_from:=public._legal_judicial_date(p_payload->>'valid_from');r.valid_until:=public._legal_judicial_date(p_payload->>'valid_until');
 perform public._legal_deadline_scope(r.scope);perform public._legal_deadline_rule_structure(r.body);perform public._legal_deadline_sources(r.sources,t);
 select coalesce(max(version_number),0)+1 into r.version_number from public.legal_deadline_rule_versions where tenant_id=t and rule_key=r.rule_key;insert into public.legal_deadline_rule_versions values(r.*) returning * into r;
 perform public._legal_judicial_event(t,null,'deadline_rule_drafted',jsonb_build_object('version_id',r.id));return r;
end;$$;
create or replace function public.legal_deadline_review_calendar(p_version_id uuid,p_decision text,p_note text) returns public.legal_deadline_calendar_versions language plpgsql security definer set search_path=pg_catalog,public,pg_temp as $$declare r public.legal_deadline_calendar_versions;t uuid:=public.legal_actual_tenant();e jsonb;begin
 if not public._legal_judicial_admin() then raise exception 'Calendar approval administration required' using errcode='42501';end if;perform pg_advisory_xact_lock(hashtextextended('legal_judicial_catalog:'||t,0));if not public._legal_judicial_admin() then raise exception 'Calendar review access revoked' using errcode='42501';end if;
 select * into r from public.legal_deadline_calendar_versions where id=p_version_id and tenant_id=t for update;if not found then raise exception 'Calendar access denied' using errcode='42501';end if;
 if p_decision not in ('approved','rejected','revoked') or (p_decision='revoked' and r.state<>'approved') or (p_decision<>'revoked' and r.state<>'draft') or length(btrim(coalesce(p_note,''))) not between 1 and 4000 then raise exception 'Explicit calendar review or revocation required' using errcode='22023';end if;
 if p_decision='approved' then
  perform public._legal_deadline_scope(r.scope,true);perform public._legal_deadline_calendar_structure(r.body,true);perform public._legal_deadline_sources(r.sources,t,true);
  if r.valid_from is null or r.valid_until is null then raise exception 'Finite complete calendar coverage required' using errcode='22023';end if;
  for e in select value from jsonb_array_elements(r.body->'exceptions') loop if (e->>'on')::date not between r.valid_from and r.valid_until or (e->>'source_index')::integer>=jsonb_array_length(r.sources) then raise exception 'Calendar exception requires in-range date and valid proof index' using errcode='22023';end if;end loop;
  for e in select value from jsonb_array_elements(r.body->'suspensions') loop if (e->>'from')::date<r.valid_from or (e->>'until')::date>r.valid_until or (e->>'source_index')::integer>=jsonb_array_length(r.sources) then raise exception 'Suspension requires complete coverage and valid proof index' using errcode='22023';end if;end loop;
 end if;
 update public.legal_deadline_calendar_versions set state=p_decision,reviewed_by=auth.uid(),reviewed_at=clock_timestamp(),review_note=btrim(p_note) where id=r.id returning * into r;perform public._legal_judicial_event(t,null,'calendar_reviewed',jsonb_build_object('version_id',r.id,'decision',p_decision));return r;
end;$$;
create or replace function public.legal_deadline_review_rule(p_version_id uuid,p_decision text,p_note text) returns public.legal_deadline_rule_versions language plpgsql security definer set search_path=pg_catalog,public,pg_temp as $$declare r public.legal_deadline_rule_versions;t uuid:=public.legal_actual_tenant();begin
 if not public._legal_judicial_admin() then raise exception 'Rule approval administration required' using errcode='42501';end if;perform pg_advisory_xact_lock(hashtextextended('legal_judicial_catalog:'||t,0));if not public._legal_judicial_admin() then raise exception 'Rule review access revoked' using errcode='42501';end if;
 select * into r from public.legal_deadline_rule_versions where id=p_version_id and tenant_id=t for update;if not found then raise exception 'Rule access denied' using errcode='42501';end if;
 if p_decision not in ('approved','rejected','revoked') or (p_decision='revoked' and r.state<>'approved') or (p_decision<>'revoked' and r.state<>'draft') or length(btrim(coalesce(p_note,''))) not between 1 and 4000 then raise exception 'Explicit rule review or revocation required' using errcode='22023';end if;
 if p_decision='approved' then
  perform public._legal_deadline_scope(r.scope,true);perform public._legal_deadline_rule_structure(r.body,true);perform public._legal_deadline_sources(r.sources,t,true);
  if r.valid_from is null or r.valid_until is null or r.body->'transition_resolved' is distinct from 'true'::jsonb or r.body->>'regime'<>'civil_procedure' or r.body->>'nature'<>'procedural' or r.body->>'anchor_kind' not in ('made_available_on','published_on','awareness_effective_on','decision_signed_at','communication_sent_at','source_consulted_at','manual_verified') then raise exception 'Finite validity, resolved transition and implemented procedural regime required' using errcode='22023';end if;
 end if;
 update public.legal_deadline_rule_versions set state=p_decision,reviewed_by=auth.uid(),reviewed_at=clock_timestamp(),review_note=btrim(p_note) where id=r.id returning * into r;perform public._legal_judicial_event(t,null,'deadline_rule_reviewed',jsonb_build_object('version_id',r.id,'decision',p_decision));return r;
end;$$;
-- Read-only reviewer/proof capability snapshot. No cross-case locks are acquired under
-- the catalog lock: concurrent revocation is reflected by the next snapshot comparison.
create or replace function public._legal_deadline_proof_access(p_reviewer_id uuid,p_tenant_id uuid,p_sources jsonb) returns jsonb language sql stable security definer set search_path=pg_catalog,public,pg_temp as $$
 select coalesce(jsonb_agg(jsonb_build_object('document_id',proof_id,'current_can_access',exists(select 1 from public.profiles reviewer join public.legal_case_documents proof on proof.id=proof_id and proof.tenant_id=p_tenant_id and proof.category='general' and proof.status='ready' join public.legal_cases proof_case on proof_case.id=proof.case_id and proof_case.tenant_id=p_tenant_id where reviewer.id=p_reviewer_id and reviewer.tenant_id=p_tenant_id and reviewer.status='active' and reviewer.role='admin' and (proof_case.owner_id=reviewer.id or exists(select 1 from public.legal_case_members member where member.case_id=proof_case.id and member.profile_id=reviewer.id)))) order by proof_id),'[]') from (select distinct (source->>'document_id')::uuid proof_id from jsonb_array_elements(coalesce(p_sources,'[]')) source where nullif(source->>'document_id','') is not null) references_list;
$$;
create or replace function public._legal_deadline_snapshot(p_case_id uuid,p_input jsonb) returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public,pg_temp as $$declare r public.legal_deadline_rule_versions;c public.legal_deadline_calendar_versions;i public.legal_judicial_inbox;d public.legal_case_documents;proofs jsonb;begin
 select * into r from public.legal_deadline_rule_versions where id=(p_input->>'rule_version_id')::uuid;select * into c from public.legal_deadline_calendar_versions where id=(p_input->>'calendar_version_id')::uuid;
 select * into i from public.legal_judicial_inbox where id=(p_input->>'inbox_id')::uuid;select * into d from public.legal_case_documents where id=(p_input->>'evidence_document_id')::uuid and case_id=p_case_id;
 select coalesce(jsonb_agg(jsonb_build_object('id',x.id,'status',x.status,'sha256',x.sha256,'category',x.category) order by x.id),'[]') into proofs from public.legal_case_documents x where x.id in(select (v->>'document_id')::uuid from jsonb_array_elements(coalesce(r.sources,'[]')||coalesce(c.sources,'[]')) v where nullif(v->>'document_id','') is not null);
 return jsonb_build_object('input',p_input,'case_owner',(select owner_id from public.legal_cases where id=p_case_id),'case_owner_active',(select p.status='active' and p.tenant_id=owner_case.tenant_id from public.legal_cases owner_case join public.profiles p on p.id=owner_case.owner_id where owner_case.id=p_case_id),'catalog_reviewers',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'status',p.status,'role',p.role,'tenant_id',p.tenant_id) order by p.id) from public.profiles p where p.id in(r.reviewed_by,c.reviewed_by)),'[]'),'proceeding',(select to_jsonb(p) from public.judicial_proceedings p where id=(p_input->>'proceeding_id')::uuid and case_id=p_case_id),
 'rule',to_jsonb(r),'calendar',to_jsonb(c),'rule_head',(select id from public.legal_deadline_rule_versions where tenant_id=r.tenant_id and rule_key=r.rule_key and state='approved' order by version_number desc limit 1),'calendar_head',(select id from public.legal_deadline_calendar_versions where tenant_id=c.tenant_id and calendar_key=c.calendar_key and state='approved' order by version_number desc limit 1),
 'catalog_proofs',proofs,'catalog_proof_access',jsonb_build_object('rule',public._legal_deadline_proof_access(r.reviewed_by,r.tenant_id,r.sources),'calendar',public._legal_deadline_proof_access(c.reviewed_by,c.tenant_id,c.sources)),'evidence',case when d.id is null then null else jsonb_build_object('id',d.id,'status',d.status,'sha256',d.sha256,'category',d.category) end,
 'inbox',case when i.id is null then null else to_jsonb(i)-array['title','temporal_notes','candidates','review_note'] end,
 'inbox_source_head',(select jsonb_build_object('id',head.id,'version_number',head.version_number,'association_state',head.association_state,'revision',head.revision,'original_sha256',head.original_sha256) from public.legal_judicial_inbox head where head.connection_id=i.connection_id and head.provider_event_id=i.provider_event_id order by head.version_number desc limit 1),
 'actors',coalesce((select jsonb_agg(jsonb_build_object('id',p.id,'status',p.status,'tenant_id',p.tenant_id,'can_handle',public._legal_judicial_actor(p_case_id,p.id),'is_owner',p.id=(select owner_id from public.legal_cases where id=p_case_id)) order by p.id) from public.profiles p where p.id in((p_input->>'assignee_id')::uuid,(p_input->>'substitute_id')::uuid)),'[]'));
end;$$;
create or replace function public._legal_deadline_current(p_version_id uuid) returns boolean language plpgsql stable security definer set search_path=pg_catalog,public,pg_temp as $$declare v public.legal_deadline_versions;begin
 select * into v from public.legal_deadline_versions where id=p_version_id;if not found then return false;end if;
 return v.snapshot_hash=encode(sha256(convert_to(public._legal_deadline_snapshot(v.case_id,v.input)::text,'UTF8')),'hex') and not exists(select 1 from public.legal_deadline_versions n where n.case_id=v.case_id and n.deadline_key=v.deadline_key and n.version_number>v.version_number);
end;$$;

create or replace function public._legal_deadline_anchor_refusals(p_input jsonb,p_rule jsonb,p_calendar jsonb,p_inbox jsonb) returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public,pg_temp as $$declare kind text:=p_input->>'anchor_kind';source_value text;expected_date date;given_date date;expected_at timestamptz;given_at timestamptz;matches boolean:=false;begin
 if kind='manual_verified' then
  if coalesce(length(btrim(p_input->>'manual_anchor_reason')),0) between 1 and 4000 and nullif(p_input->>'evidence_document_id','') is not null then return '[]';end if;
  return jsonb_build_array(jsonb_build_object('code','manual_anchor_unexplained','message','Marco manual exige prova e justificativa própria, separada da duração.'));
 end if;
 if kind is null or kind not in ('made_available_on','published_on','awareness_effective_on','decision_signed_at','communication_sent_at','source_consulted_at') then return jsonb_build_array(jsonb_build_object('code','unsupported_source_anchor','message','Escolha um campo jurídico comprovado da fonte ou registre marco manual fundamentado.'));end if;
 source_value:=p_inbox->>kind;
 if p_inbox->>'id' is null or source_value is null then return jsonb_build_array(jsonb_build_object('code','source_anchor_missing','message','A fonte conferida não informa o marco selecionado. Não usar captura ou mensagem do fornecedor como substituto.'));end if;
 if kind in ('made_available_on','published_on','awareness_effective_on') then
  if p_rule->'body'->>'input_kind'='timestamp' then return jsonb_build_array(jsonb_build_object('code','source_anchor_precision','message','A fonte informa somente data civil; não inventar horário ou fuso.'));end if;
  expected_date:=public._legal_judicial_date(source_value);given_date:=public._legal_judicial_date(p_input->>'anchor_date');matches:=expected_date=given_date;
 else
  expected_at:=source_value::timestamptz;
  if p_rule->'body'->>'input_kind'='timestamp' then given_at:=public._legal_judicial_timestamp(p_input->>'anchor_at');matches:=expected_at=given_at;
  elsif p_calendar->>'timezone' is not null then expected_date:=(expected_at at time zone (p_calendar->>'timezone'))::date;given_date:=public._legal_judicial_date(p_input->>'anchor_date');matches:=expected_date=given_date;end if;
 end if;
 if matches is distinct from true then return jsonb_build_array(jsonb_build_object('code','source_anchor_mismatch','message','O marco informado diverge do campo da fonte no fuso do órgão. Corrija ou documente um marco manual alternativo.'));end if;return '[]';
exception when invalid_datetime_format or datetime_field_overflow or invalid_parameter_value then return jsonb_build_array(jsonb_build_object('code','invalid_source_anchor','message','Data, instante ou fuso do marco precisa de conferência.'));
end;$$;

create or replace function public.legal_deadline_create_version(p_case_id uuid,p_payload jsonb) returns public.legal_deadline_versions language plpgsql security definer set search_path=pg_catalog,public,pg_temp as $$declare t uuid:=public._legal_judicial_assert(p_case_id,'restricted');v public.legal_deadline_versions;old public.legal_deadline_versions;r public.legal_deadline_rule_versions;c public.legal_deadline_calendar_versions;i public.legal_judicial_inbox;d public.legal_case_documents;refusals jsonb:='[]';a uuid;begin
 perform public._legal_judicial_payload(p_payload,array['deadline_key','title','proceeding_id','inbox_id','rule_version_id','calendar_version_id','quantity','unit','anchor_date','anchor_at','anchor_kind','evidence_document_id','duration_basis','manual_anchor_reason','conditions_confirmed','coverage_confirmed','conflict_detected','scope','assignee_id','substitute_id','note','supersedes_version_id']);
 if octet_length(p_payload::text)>30000 or coalesce(length(p_payload->>'note'),0)>4000 or coalesce(length(p_payload->>'duration_basis'),0)>4000 then raise exception 'Bounded deadline input required' using errcode='22023';end if;
 perform pg_advisory_xact_lock(hashtextextended('legal_judicial_catalog:'||t,0));perform public._legal_judicial_assert(p_case_id,'restricted');
 if not exists(select 1 from public.judicial_proceedings where id=(p_payload->>'proceeding_id')::uuid and case_id=p_case_id and tenant_id=t) then raise exception 'Same-case judicial proceeding required' using errcode='42501';end if;
 if not exists(select 1 from public.judicial_proceedings proceeding where proceeding.id=(p_payload->>'proceeding_id')::uuid and nullif(btrim(proceeding.court),'') is not null and proceeding.court=p_payload->'scope'->>'court') then refusals:=refusals||jsonb_build_array(jsonb_build_object('code','proceeding_scope_mismatch','message','O órgão da regra e do calendário deve corresponder ao processo cadastrado. Complete ou confira esse vínculo.'));end if;
 foreach a in array array[(p_payload->>'assignee_id')::uuid,(p_payload->>'substitute_id')::uuid] loop if a is not null and not public._legal_judicial_actor(p_case_id,a) then raise exception 'Current case participants with both category grants required' using errcode='22023';end if;end loop;
 if nullif(p_payload->>'assignee_id','') is null or (p_payload->>'substitute_id') is not null and p_payload->>'substitute_id'=p_payload->>'assignee_id' then raise exception 'Explicit distinct responsible and substitute required' using errcode='22023';end if;
 if nullif(p_payload->>'rule_version_id','') is not null then select * into r from public.legal_deadline_rule_versions where id=(p_payload->>'rule_version_id')::uuid and tenant_id=t;if not found then raise exception 'Rule tenant access denied' using errcode='42501';end if;end if;
 if nullif(p_payload->>'calendar_version_id','') is not null then select * into c from public.legal_deadline_calendar_versions where id=(p_payload->>'calendar_version_id')::uuid and tenant_id=t;if not found then raise exception 'Calendar tenant access denied' using errcode='42501';end if;end if;
 if nullif(p_payload->>'inbox_id','') is not null then select * into i from public.legal_judicial_inbox where id=(p_payload->>'inbox_id')::uuid and case_id=p_case_id;if not found then raise exception 'Source event case access denied' using errcode='42501';end if;
  if i.connection_id is not null and exists(select 1 from public.legal_judicial_inbox newer where newer.connection_id=i.connection_id and newer.provider_event_id=i.provider_event_id and newer.version_number>i.version_number and newer.association_state<>'rejected') then refusals:=refusals||jsonb_build_array(jsonb_build_object('code','source_correction_pending','message','Existe nova versão da fonte ainda não rejeitada em revisão. Conferir a correção antes do prazo.'));end if;
  if i.association_state<>'confirmed' or i.proceeding_id<>(p_payload->>'proceeding_id')::uuid then refusals:=refusals||jsonb_build_array(jsonb_build_object('code','unconfirmed_association','message','Conferir associação da fonte ao processo antes do prazo.'));end if;
 end if;
 if nullif(p_payload->>'evidence_document_id','') is not null then d:=public._legal_judicial_document(p_case_id,(p_payload->>'evidence_document_id')::uuid);else refusals:=refusals||jsonb_build_array(jsonb_build_object('code','missing_evidence','message','Anexar e conferir prova do marco.'));end if;
 if r.id is not null and (not exists(select 1 from public.profiles where id=r.reviewed_by and tenant_id=t and role='admin' and status='active') or exists(select 1 from public.legal_deadline_rule_versions n where n.tenant_id=t and n.rule_key=r.rule_key and n.version_number>r.version_number and n.state='approved')) then refusals:=refusals||jsonb_build_array(jsonb_build_object('code','rule_review_unavailable','message','A regra precisa da aprovação atual de responsável ativo.'));end if;
 if c.id is not null and (not exists(select 1 from public.profiles where id=c.reviewed_by and tenant_id=t and role='admin' and status='active') or exists(select 1 from public.legal_deadline_calendar_versions n where n.tenant_id=t and n.calendar_key=c.calendar_key and n.version_number>c.version_number and n.state='approved')) then refusals:=refusals||jsonb_build_array(jsonb_build_object('code','calendar_review_unavailable','message','O calendário precisa da aprovação atual de responsável ativo.'));end if;
 if exists(select 1 from jsonb_array_elements(public._legal_deadline_proof_access(r.reviewed_by,t,r.sources)||public._legal_deadline_proof_access(c.reviewed_by,t,c.sources)) proof_access where proof_access->'current_can_access' is distinct from 'true'::jsonb) then refusals:=refusals||jsonb_build_array(jsonb_build_object('code','catalog_reviewer_evidence_unavailable','message','O revisor da regra ou calendário perdeu acesso à prova. Nova revisão documental é necessária.'));end if;
 refusals:=refusals||public._legal_deadline_anchor_refusals(p_payload,to_jsonb(r),to_jsonb(c),to_jsonb(i));
 if exists(select 1 from jsonb_array_elements(coalesce(r.sources,'[]')||coalesce(c.sources,'[]')) s where not exists(select 1 from public.legal_case_documents proof where proof.id=(s->>'document_id')::uuid and proof.tenant_id=t and proof.category='general' and proof.status='ready')) then refusals:=refusals||jsonb_build_array(jsonb_build_object('code','catalog_evidence_unavailable','message','Revisar a prova documental da regra e do calendário.'));end if;
 select * into old from public.legal_deadline_versions where case_id=p_case_id and deadline_key=p_payload->>'deadline_key' order by version_number desc limit 1;
 if old.id is not null and (p_payload->>'supersedes_version_id')::uuid is distinct from old.id then raise exception 'New deadline version must explicitly reference the latest historical version' using errcode='22023';end if;
 if old.id is null and nullif(p_payload->>'supersedes_version_id','') is not null then raise exception 'No previous deadline version exists for this key' using errcode='22023';end if;
 v.id:=gen_random_uuid();v.tenant_id:=t;v.case_id:=p_case_id;v.deadline_key:=p_payload->>'deadline_key';v.title:=p_payload->>'title';v.version_number:=coalesce(old.version_number,0)+1;v.category:='restricted';v.proceeding_id:=(p_payload->>'proceeding_id')::uuid;v.inbox_id:=i.id;v.rule_version_id:=r.id;v.calendar_version_id:=c.id;v.input:=p_payload;v.snapshot:=public._legal_deadline_snapshot(p_case_id,p_payload);v.snapshot_hash:=encode(sha256(convert_to(v.snapshot::text,'UTF8')),'hex');v.engine_version:='legal-deadline-v1';v.result:=public._legal_deadline_compute(p_payload,to_jsonb(r),to_jsonb(c));
 if jsonb_array_length(refusals)>0 then v.result:=v.result||jsonb_build_object('proposed_due_on',null,'due_at',null,'refusals',coalesce(v.result->'refusals','[]')||refusals);end if;
 v.state:=case when jsonb_array_length(v.result->'refusals')>0 or v.result->>'proposed_due_on' is null then 'incomplete' else 'draft' end;v.created_by:=auth.uid();v.created_at:=clock_timestamp();v.review_note:='';v.supersedes_version_id:=old.id;
 insert into public.legal_deadline_versions values(v.*) returning * into v;perform public._legal_judicial_event(t,p_case_id,'deadline_proposed',jsonb_build_object('version_id',v.id,'state',v.state));return v;
end;$$;
create or replace function public.legal_deadline_submit(p_version_id uuid) returns public.legal_deadline_versions language plpgsql security definer set search_path=pg_catalog,public,pg_temp as $$declare v public.legal_deadline_versions;begin
 select * into v from public.legal_deadline_versions where id=p_version_id;perform public._legal_judicial_assert(v.case_id,'restricted');perform pg_advisory_xact_lock(hashtextextended('legal_judicial_catalog:'||v.tenant_id,0));select * into v from public.legal_deadline_versions where id=p_version_id for update;perform public._legal_judicial_assert(v.case_id,'restricted');
 if v.state<>'draft' or not public._legal_deadline_current(v.id) or jsonb_array_length(v.result->'refusals')>0 then raise exception 'Only a complete current draft may enter deadline review' using errcode='22023';end if;
 update public.legal_deadline_versions set state='in_review' where id=v.id returning * into v;perform public._legal_judicial_event(v.tenant_id,v.case_id,'deadline_submitted',jsonb_build_object('version_id',v.id));return v;
end;$$;
create or replace function public.legal_deadline_review(p_version_id uuid,p_decision text,p_note text) returns public.legal_deadline_versions language plpgsql security definer set search_path=pg_catalog,public,pg_temp as $$declare v public.legal_deadline_versions;task public.legal_case_tasks;a uuid;begin
 select * into v from public.legal_deadline_versions where id=p_version_id;perform public._legal_judicial_assert(v.case_id,'restricted',true);perform pg_advisory_xact_lock(hashtextextended('legal_judicial_catalog:'||v.tenant_id,0));select * into v from public.legal_deadline_versions where id=p_version_id for update;perform public._legal_judicial_assert(v.case_id,'restricted',true);
 if p_decision not in ('reviewed','returned') or length(btrim(coalesce(p_note,''))) not between 1 and 4000 or v.state not in ('incomplete','draft','in_review') then raise exception 'Reviewable version and explicit decision required' using errcode='22023';end if;
 if p_decision='reviewed' then
  if v.state<>'in_review' or not public._legal_deadline_current(v.id) or v.result->>'proposed_due_on' is null or v.result->>'due_at' is null or jsonb_array_length(v.result->'refusals')>0 then raise exception 'Complete current submitted version required before a reviewed deadline task' using errcode='22023';end if;
  foreach a in array array[(v.input->>'assignee_id')::uuid,(v.input->>'substitute_id')::uuid] loop if a is not null and not public._legal_judicial_actor(v.case_id,a) then raise exception 'Responsible source category permission revoked' using errcode='42501';end if;end loop;
  task:=public._legal_f2_save_case_task(v.case_id,jsonb_build_object('title','Acompanhar prazo judicial','notes','Consultar versão, memória e atualidade no módulo judicial antes de agir. Tarefa interna não executa protocolo.','assignee_id',v.input->>'assignee_id','substitute_id',v.input->>'substitute_id','due_at',v.result->>'due_at'));
  insert into public.legal_judicial_task_links(task_id,tenant_id,case_id,category,reference_kind,reference_id) values(task.id,v.tenant_id,v.case_id,'restricted','deadline_reviewed',v.id);
 end if;
 update public.legal_deadline_versions set state=p_decision,reviewed_by=auth.uid(),reviewed_at=clock_timestamp(),review_note=btrim(p_note),task_id=task.id where id=v.id returning * into v;
 insert into public.legal_deadline_reviews(tenant_id,case_id,version_id,decision,snapshot_hash,note,reviewed_by) values(v.tenant_id,v.case_id,v.id,p_decision,v.snapshot_hash,btrim(p_note),auth.uid());perform public._legal_judicial_event(v.tenant_id,v.case_id,'deadline_reviewed',jsonb_build_object('version_id',v.id,'decision',p_decision,'task_id',task.id));return v;
end;$$;
create or replace function public.legal_deadline_create_check_task(p_version_id uuid,p_due_at timestamptz,p_note text) returns public.legal_case_tasks language plpgsql security definer set search_path=pg_catalog,public,pg_temp as $$declare v public.legal_deadline_versions;task public.legal_case_tasks;a uuid;begin
 select * into v from public.legal_deadline_versions where id=p_version_id;perform public._legal_judicial_assert(v.case_id,'restricted');
 if p_due_at is not null and not isfinite(p_due_at) or length(btrim(coalesce(p_note,''))) not between 1 and 2000 then raise exception 'Finite internal review date and reason required' using errcode='22023';end if;
 select t.* into task from public.legal_case_tasks t join public.legal_judicial_task_links l on l.task_id=t.id where l.reference_id=v.id and l.reference_kind='deadline_check' and t.status='open' order by t.created_at limit 1;if found then return task;end if;
 foreach a in array array[(v.input->>'assignee_id')::uuid,(v.input->>'substitute_id')::uuid] loop if a is not null and not public._legal_judicial_actor(v.case_id,a) then raise exception 'Current assigned category permissions required; create a corrected proposal if necessary' using errcode='42501';end if;end loop;
 task:=public._legal_f2_save_case_task(v.case_id,jsonb_build_object('title','Conferir prazo judicial','notes','Conferência pendente; esta tarefa não representa prazo processual aprovado.','assignee_id',v.input->>'assignee_id','substitute_id',v.input->>'substitute_id','due_at',p_due_at));
 insert into public.legal_judicial_task_links(task_id,tenant_id,case_id,category,reference_kind,reference_id) values(task.id,v.tenant_id,v.case_id,'restricted','deadline_check',v.id);perform public._legal_judicial_event(v.tenant_id,v.case_id,'deadline_check_requested',jsonb_build_object('version_id',v.id,'task_id',task.id));return task;
end;$$;
create or replace function public.legal_deadline_read_report(p_version_id uuid) returns jsonb language plpgsql security definer set search_path=pg_catalog,public,pg_temp as $$declare v public.legal_deadline_versions;begin
 select * into v from public.legal_deadline_versions where id=p_version_id;if not found then raise exception 'Deadline access denied' using errcode='42501';end if;perform 1 from public.legal_cases where id=v.case_id for update;
 if not public.legal_judicial_can_access(v.case_id,'restricted') then raise exception 'Current dual category access required' using errcode='42501';end if;select * into v from public.legal_deadline_versions where id=p_version_id;
 perform public._legal_judicial_event(v.tenant_id,v.case_id,'deadline_report_read',jsonb_build_object('version_id',v.id));return jsonb_build_object('calculation',to_jsonb(v),'is_current',public._legal_deadline_current(v.id),'generated_at',clock_timestamp());
end;$$;

create or replace function public._legal_judicial_context_base(p_case_id uuid default null) returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public,pg_temp as $$declare t uuid:=public.legal_actual_tenant();is_admin boolean:=public._legal_judicial_admin();begin
 if t is null or not public.legal_feature_enabled() or (p_case_id is not null and not public.legal_can_access_case(p_case_id)) then raise exception 'Judicial workspace access denied' using errcode='42501';end if;
 return jsonb_build_object('tenant_id',t,'user_id',auth.uid(),'can_manage_sources',is_admin,'can_edit_catalog',public.legal_can_create(),'can_approve_catalog',is_admin,'can_edit_case',coalesce(public.legal_can_access_case(p_case_id,true) and public.legal_judicial_can_access(p_case_id,'restricted'),false),'can_review_case',coalesce(public.legal_can_access_case(p_case_id,true,true) and public.legal_judicial_can_access(p_case_id,'restricted'),false),
 'sources',coalesce((select jsonb_agg(to_jsonb(s) order by created_at desc,id) from public.legal_judicial_source_versions s where tenant_id=t),'[]'),
 'connections',coalesce((select jsonb_agg(public._legal_judicial_connection_projection(c) order by created_at,id) from public.legal_judicial_connections c where tenant_id=t),'[]'),
 'coverages',coalesce((select jsonb_agg(to_jsonb(c)||jsonb_build_object('is_late',c.last_capture_at is null or c.last_capture_at+make_interval(mins=>c.expected_interval_minutes+c.tolerated_delay_minutes)<clock_timestamp()) order by reviewed_at,id) from public.legal_judicial_coverages c where tenant_id=t),'[]'),
 'jobs',coalesce((select jsonb_agg(public._legal_judicial_job_projection(j) order by created_at desc,id) from public.legal_judicial_jobs j where tenant_id=t and ((p_case_id is null and j.case_id is null and is_admin) or (j.case_id=p_case_id and public.legal_judicial_can_access(j.case_id,'restricted')))),'[]'),
 'inbox',coalesce((select jsonb_agg(to_jsonb(i) order by coalesce(i.source_updated_at,i.captured_at) desc,i.version_number desc,i.id) from public.legal_judicial_inbox i where tenant_id=t and ((p_case_id is null and i.case_id is null and is_admin) or (i.case_id=p_case_id and public.legal_judicial_can_access(i.case_id,i.category)))),'[]'),
 'triage',coalesce((select jsonb_agg(to_jsonb(r) order by internal_received_at desc,r.id) from public.legal_judicial_triage r join public.legal_judicial_inbox i on i.id=r.inbox_id where r.case_id=p_case_id and public.legal_judicial_can_access(r.case_id,i.category)),'[]'),
 'calendars','[]'::jsonb,'rules','[]'::jsonb,'deadlines','[]'::jsonb,'deadline_states','[]'::jsonb);
end;$$;
create or replace function public.legal_judicial_context(p_case_id uuid default null) returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public,pg_temp as $$declare result jsonb;t uuid:=public.legal_actual_tenant();begin
 result:=public._legal_judicial_context_base(p_case_id);
 return result||jsonb_build_object('calendars',coalesce((select jsonb_agg(to_jsonb(c) order by created_at desc,id) from public.legal_deadline_calendar_versions c where tenant_id=t),'[]'),'rules',coalesce((select jsonb_agg(to_jsonb(r) order by created_at desc,id) from public.legal_deadline_rule_versions r where tenant_id=t),'[]'),
 'deadlines',coalesce((select jsonb_agg(to_jsonb(v) order by created_at desc,id) from public.legal_deadline_versions v where case_id=p_case_id and public.legal_judicial_can_access(case_id,'restricted')),'[]'),
 'deadline_states',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'is_current',public._legal_deadline_current(v.id),'needs_review',v.state='reviewed' and not public._legal_deadline_current(v.id)) order by created_at desc,id) from public.legal_deadline_versions v where case_id=p_case_id and public.legal_judicial_can_access(case_id,'restricted')),'[]'));
end;$$;

-- Stale references become an explicit review item; historical due dates remain unchanged.
create or replace function public.legal_my_day(p_from timestamptz,p_until timestamptz,p_limit integer default 50,p_offset integer default 0) returns jsonb language plpgsql stable security definer set search_path=pg_catalog,public,pg_temp as $$
declare result jsonb;begin
 if public.legal_actual_tenant() is null or not public.legal_feature_enabled() then raise exception 'Active legal workspace required' using errcode='42501';end if;
 if p_from is null or p_until is null or not isfinite(p_from) or not isfinite(p_until) or p_until<=p_from or p_limit not between 1 and 100 or p_offset not between 0 and 100000 then raise exception 'Invalid work queue range or pagination' using errcode='22023';end if;
 with items as (
 select id,case_id,'task'::text kind,case when exists(select 1 from public.legal_judicial_task_links l where l.task_id=legal_case_tasks.id and l.reference_kind='deadline_reviewed' and not public._legal_deadline_current(l.reference_id)) then 'Reconferir prazo judicial: referência alterada' else title end title,due_at,status,assignee_id,id source_id from public.legal_case_tasks where public.legal_judicial_can_read_task(id,case_id) and status='open' and (assignee_id=auth.uid() or substitute_id=auth.uid())
 union all select id,case_id,'appointment',title,starts_at,status,assignee_id,id from public.legal_appointments where public.legal_can_access_case(case_id) and status='scheduled' and (assignee_id=auth.uid() or substitute_id=auth.uid())
 union all select r.id,r.case_id,'waiting_client',r.title,r.due_at,q.status,r.created_by,r.id from public.legal_portal_requests r join public.legal_document_requests q on q.id=r.request_id where public.legal_can_access_category(r.case_id,r.category) and q.status in ('open','submitted','uploading') and r.created_by=auth.uid()
 union all select r.id,r.case_id,'withholding_reopened','Retenção retomada: conferir documentação',null::timestamptz,r.status,r.reviewer_id,r.id from public.ir_cessation_records r where public.legal_can_access_category(r.case_id,'fiscal') and r.reviewer_id=auth.uid() and r.status='reopened' and not exists(select 1 from public.ir_cessation_records newer where newer.source_id=r.source_id and (newer.observed_on,newer.created_at,newer.id)>(r.observed_on,r.created_at,r.id))
 union all select j.id,j.case_id,'communication','Revisar estado da comunicação',j.updated_at,j.state,c.reviewed_by,c.id from public.legal_communication_jobs j join public.legal_communication_versions c on c.id=j.communication_id where public.legal_can_access_category(c.case_id,c.category) and j.state in ('failed','unknown') and c.reviewed_by=auth.uid()
 ),page as(select * from items where due_at is null or (due_at>=p_from and due_at<p_until) order by due_at nulls last,id limit p_limit+1 offset p_offset)
 select jsonb_build_object('items',coalesce((select jsonb_agg(to_jsonb(x) order by due_at nulls last,id) from (select * from page limit p_limit) x),'[]'),'has_more',(select count(*)>p_limit from page)) into result;return result;
end;$$;
do $$declare tab text;fn record;begin
 foreach tab in array array['legal_deadline_calendar_versions','legal_deadline_rule_versions','legal_deadline_versions','legal_deadline_reviews'] loop
  execute format('alter table public.%I enable row level security',tab);execute format('revoke all on public.%I from public,anon,authenticated,legal_portal,service_role',tab);execute format('grant select on public.%I to authenticated,service_role',tab);
 end loop;
 foreach tab in array array['legal_deadline_calendar_versions','legal_deadline_rule_versions'] loop execute format('create policy legal_deadline_catalog_read on public.%I for select to authenticated using(tenant_id=public.legal_actual_tenant() and public.legal_feature_enabled())',tab);end loop;
 foreach tab in array array['legal_deadline_versions','legal_deadline_reviews'] loop execute format('create policy legal_deadline_case_read on public.%I for select to authenticated using(public.legal_judicial_can_access(case_id,''restricted''))',tab);end loop;
 for fn in select p.oid::regprocedure sig,p.proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and (p.proname like '\_legal\_deadline\_%' escape '\' or p.proname like 'legal\_deadline\_%' escape '\' or p.proname='_legal_judicial_context_base') loop
  execute format('revoke all on function %s from public,anon,authenticated,legal_portal,service_role',fn.sig);if fn.proname like 'legal_deadline_%' then execute format('grant execute on function %s to authenticated',fn.sig);end if;
 end loop;
end;$$;
notify pgrst,'reload schema';
